waffle:
  home-dir: /tmp/.waffle_home

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:${waffle.home-dir}/waffle_h2;MODE=MYSQL
    username: sa
    password:
    data:
      - classpath:sql/data/h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      