waffle:
  home-dir: ~/.waffle_home

spring:
  profiles:
    active: production
    
  h2:
    console:
      enabled: false
      
server:
  session:
    persistent: false

security:
  basic:
    enabled: false
