spring:
  profiles:
    active: production
    
  data:
    neo4j:
      embedded:
        enabled: true

  devtools:
    restart:
      enabled: false

server:
  session:
    persistent: false
    tracking-modes: "cookie"

security:
  basic:
    enabled: false

management:
  add-application-context-header: false
