spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    data:
      - classpath:sql/data/h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      